theme: jekyll-theme-minimal
title: GRaViTY Tool
description: The GRaViTY tool is a research prototype for the analysis of software design and security, evaluation and execution of refactorings and automated software optimization.
